# Generated by Django 5.0.4 on 2024-04-13 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория ')),
                ('url', models.SlugField(max_length=100, unique=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Язык ')),
                ('url', models.SlugField(max_length=100, unique=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Kyrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name ')),
                ('img', models.ImageField(blank=True, null=True, upload_to='kyrs/', verbose_name='фото')),
                ('money', models.CharField(max_length=150, verbose_name='Цена ')),
                ('content', models.TextField()),
                ('url', models.SlugField(max_length=100, unique=True, verbose_name='url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ползывитель')),
                ('lan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language', verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name ')),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='video/')),
                ('kyrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kyrs')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя ')),
                ('text', models.TextField(verbose_name='Сообщениие')),
                ('kyrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kyrs', verbose_name='курс')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='question ')),
                ('correct_answer', models.CharField(max_length=100, verbose_name='correct_answer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='main.lesson')),
            ],
        ),
    ]
